route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: https://webhook.site/76d23f5a-713c-40ac-a7b1-024174776ce3
          send_resolved: false
