# syntax=docker/dockerfile:1.4
FROM python:3.12-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./
COPY gunicorn_config.py gunicorn_config.py
RUN apk add --no-cache \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev \
    cargo \
    make \
    linux-headers \
    python3-dev

RUN    python -m venv .venv
RUN    .venv/bin/pip3 install -r requirements.txt
RUN    chmod +x boot.sh
RUN  chown -R microblog:microblog ./


ENV FLASK_APP=microblog.py
USER microblog

ENV PROMETHEUS_MULTIPROC_DIR /tmp

EXPOSE 5000
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 CMD curl --fail http://localhost:8000/ || exit 1
ENTRYPOINT ["./boot.sh"]
