
- name: Copy prometheus config files to the server
  template:
    src: files/prometheus.yml
    dest: prometheus.yml


- name: Copy alertmanager config files to the server
  template:
    src: files/alertmanager.yml
    dest: alertmanager.yml




