
- name: Copy nginx config files to the server
  template:
    src: files/prometheus.yml
    dest: prometheus.yml


- name: Copy nginx config files to the server5
  template:
    src: files/alertmanager.yml
    dest: alertmanager.yml




