---
- name: Pull MySQL Docker image
  docker_image:
    name: mysql
    tag: latest
    source: pull

- name: Start MySQL container
  docker_container:
    name: mysql_database
    image: mysql:latest
    state: started
    restart_policy: always
    env:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: microblog
      MYSQL_USER: microblog
      MYSQL_PASSWORD: database-password
    ports:
      - "3306:3306"

      