global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
  - job_name: "nginx"
    metrics_path: /prometheus
    static_configs:
      - targets: ["microblogdev.tech:9113"]
