---
# Dra ner Microblog-bilden
- name: Install jq
      command: sudo apt-get install -y jq
  
    - name: jq latest
      uri:
        url: "https://api.github.com/repos/WeirdnessUnfolds/microblog/releases/latest"
        body_format: json
      register: _latest_tag_output
      until: _latest_tag_output.status == 200
      retries: 5

    - name: Set latest tag fact
      set_fact:
        latest_tag: "{{ _latest_tag_output.json.tag_name }}"
        
- name: Restart the Microblog application and pull latest tag
      docker_container:
        name: microblog
        image: weirdnessunfolds/devops:{{ latest_tag }}
        pull: yes
        restart: yes
        state: started
        restart_policy: always
        env:
          SECRET_KEY: "my-secret-key"
          DATABASE_URL: "mysql+pymysql://microblog:database-password@{{ groups.database[0] }}/microblog"
        ports:
        - "8000:5000"
        command: gunicorn -b 0.0.0.0:8000 -w 4 microblog:app
