---
- name: Continuous Deployment for Microblog
  hosts: some_appservers
  serial: 1  # Rullar ut en server i taget
  remote_user: deploy
  become: yes
  become_method: sudo

  tasks:
    - name: Install jq
      command: sudo apt-get install -y jq
  
    - name: jq latest
      command: curl -s "https://api.github.com/repos/WeirdnessUnfolds/microblog/releases/latest" | jq -r '.tag_name'
      register: latest_tag_output
    - debug: var=latest_tag_output
    - name: Set latest fact fact
      set_fact:
        latest_tag: "{{ latest_tag_output.stdout }}"

    - name: Pull the latest Docker image for Microblog
      ansible.builtin.docker_image:
        name: weirdnessunfolds/devops:{{ latest_tag }}
        source: pull
      
    - name: Install dependencies
      command: npm install
      args:
        chdir: /var/www/microblog

    - name: Restart the Microblog application
      service:
        name: microblog
        state: restarted

    - name: Check application health
      uri:
        url: "http://{{ inventory_hostname }}"
        status_code: 200
      register: health_check

    - name: Fail if health check fails
      fail:
        msg: "Health check failed for {{ inventory_hostname }}"
      when: health_check.status != 200
