---
- name: Continuous Deployment for Microblog
  hosts: some_appservers
  serial: 1  # Rullar ut en server i taget
  remote_user: deploy
  become: yes
  become_method: sudo

  tasks:
    - name: Install jq
      command: sudo apt-get install -y jq
  
    - name: jq latest
      uri:
        url: "https://api.github.com/repos/WeirdnessUnfolds/microblog/releases/latest"
        body_format: json
      register: _latest_tag_output
      until: _latest_tag_output.status == 200
      retries: 5

    - name: Set latest tag fact
      set_fact:
        latest_tag: "{{ _latest_tag_output.json.tag_name }}"

    - name: Pull the latest Docker image for Microblog
      ansible.builtin.docker_image:
        name: weirdnessunfolds/devops:{{ latest_tag }}
        source: pull

    - name: Debug latest tag
      debug:
        var: latest_tag
      
    - name: Restart the Microblog application and pull latest tag
      docker_container:
        name: microblog
        image: weirdnessunfolds/devops:{{ latest_tag }}
        pull: yes
        restart: yes
        state: started
        restart_policy: always
        ports:
          - "8000:5000"
        command: gunicorn -b 0.0.0.0:8000 -w 4 microblog:app

    - name: Get Docker container details
      docker_container_info:
        name: microblog
      register: container_details

    
    - name: Extract image tag
      set_fact:
        image_tag: "{{ container_details.container.Config.Image | split(':') | last }}"

    - name: Debug container details
      debug:
        var: container_details.container
    - name: Debug image tag
      debug:
        var: image_tag

    - name: Assert correct version is running
      assert:
        that:
          - image_tag == latest_tag
        fail_msg: "Deployed version is incorrect on {{ inventory_hostname }}"
