---
- name: Continuous Deployment for Microblog
  hosts: some_appservers
  serial: 1  # Rullar ut en server i taget
  remote_user: deploy
  become: yes
  become_method: sudo

  tasks:
    - name: Install jq
      command: sudo apt-get install jq
  
    - name: jq latest
      command: latest_tag=$(curl -s "https://api.github.com/repos/WeirdnessUnfolds/microblog/releases/latest" | jq -r '.tag_name')
  
  - name: Pull the latest Docker image for Microblog
      ansible.builtin.docker_image:
        name: weirdnessunfolds/devops:$latest_tag
        source: pull
      
    - name: Install dependencies
      command: npm install
      args:
        chdir: /var/www/microblog

    - name: Restart the Microblog application
      service:
        name: microblog
        state: restarted

    - name: Check application health
      uri:
        url: "http://{{ inventory_hostname }}/health"
        status_code: 200
      register: health_check

    - name: Fail if health check fails
      fail:
        msg: "Health check failed for {{ inventory_hostname }}"
      when: health_check.status != 200

    - name: Verify application version
      uri:
        url: "http://{{ inventory_hostname }}/version"
        return_content: yes
      register: version_check

    - name: Assert correct version is running
      assert:
        that:
          - "'1.0.0' in version_check.content"
        fail_msg: "Deployed version is incorrect on {{ inventory_hostname }}"
