# Gather facts from remote instance and set as hosts
---
-   hosts: local
    connection: local
    gather_facts: False
    collections:
        - azure.azcollection
    roles:
        - gather_instances

# Steg 5: Skapa säkerhetsgrupper
- name: Create security groups
  hosts: local
  gather_facts: false
  roles:
    - security_groups
