---
- name: Setup prometheus
  hosts: monitor
  remote_user: deploy
  become: yes
  become_method: sudo
  no_log: false
  roles:
    - monitor-setup-prometheus
    - role: prometheus.prometheus.prometheus
      vars:
        prometheus_config_file: prometheus.yml
    - role: prometheus.prometheus.alertmanager
      vars:
        alertmanager_config_file: alertmanager.yml

    
- name: Check if Prometheus is running
  hosts: monitor
  remote_user: deploy
  become: yes
  become_method: sudo
  tasks:
    - name: Wait for Prometheus to be available
      uri:
        url: "http://localhost:9090/-/ready"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 10
      delay: 5

