---
- name: Setup prometheus
  hosts: monitor
  remote_user: deploy
  become: yes
  become_method: sudo
  no_log: false
  module_defaults:
    group/community.grafana.grafana:
      grafana_url: "http://localhost:3000"
      grafana_user: "admin"
      grafana_password: "admin"
  roles:
    - monitor-setup-prometheus
    - role: prometheus.prometheus.prometheus
      vars:
          prometheus_config_file: /etc/prometheus/prometheus.yml
    - role: prometheus.alertmanager
      vars:
          alertmanager_config_file: /etc/prometheus/alertmanager.yml


grafana:
  image: grafana/grafana:latest
  restart: unless-stopped
  ports:
    - "3000:3000"
    - name: Setup Grafana
      hosts: monitor
      remote_user: deploy
      become: yes
      become_method: sudo
      tasks:
        - name: Pull Grafana Docker image
          community.docker.docker_image:
            name: grafana/grafana
            tag: latest
            source: pull

        - name: Run Grafana container
          community.docker.docker_container:
            name: grafana
            image: grafana/grafana:latest
            state: started
            restart_policy: unless-stopped
            ports:
              - "3000:3000"