---
-   hosts:
        -   monitor
    remote_user: deploy
    become: yes
    become_method: sudo
    roles:
        - monitor-setup-prometheus
        - monitor-setup-grafana
        - monitor-setup-alertmanager
