---
- name: Setup prometheus
  hosts: monitor
  remote_user: deploy
  become: yes
  debugger: on_failed
  become_method: sudo
  no_log: false
  roles:
    - monitor-setup-prometheus
    - role: prometheus.prometheus.prometheus
      vars:
        prometheus_config_file: prometheus.yml
    - role: prometheus.prometheus.alertmanager
      vars:
        alertmanager_config_file: alertmanager.yml

    
- name: Check if Prometheus is running
  hosts: monitor
  remote_user: deploy
  become: yes
  become_method: sudo
  tasks:
    - name: Pull Grafana Docker image
      community.docker.docker_image:
        name: grafana/grafana
        tag: latest
        source: pull

    - name: Run Grafana container
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "3000:3000"
        volumes:
          - "/monitor-setup-prometheus/files/grafana.ini:/etc/grafana/grafana.ini"

      
    - name: Wait for Grafana to be available
      uri:
        url: "http://localhost:9090/-/ready"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 10
      delay: 5

