global:
  scrape_interval: 30s

# scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
  - job_name: "nginx"
    metrics_path: /prometheus
    static_configs:
      - targets: ["microblogdev.tech:9113"]
  - job_name: "flask"
    metrics_path: /metrics
    static_configs:
      - targets: ["microblogdev.tech:5000"]
  - job_name: "alertmanager"
    metrics_path: /alertmanager
    static_configs:
      - targets: ["microblogdev.tech:9093"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "microblogdev.tech:9093"


rule_files:
  - "rules.yml"