---
# Provision servers on Azure

# Steg 1: Lägg till VM-instanser som hosts
- name: Add instances to hosts
  hosts: local
  gather_facts: false
  tasks:
    - include_vars: roles/provision_instances/vars/main.yml
    - include_tasks: roles/provision_instances/tasks/add_vms_as_hosts.yml

# Steg 2: Skapa nätverk
- name: Create networks
  hosts: local
  gather_facts: false
  tasks:
    - include_tasks: roles/provision_instances/tasks/vnet.yml
  collections:
    - azure.azcollection

# Steg 3: Samla information om instanser
- name: Gather instance information
  hosts: local
  gather_facts: false
  roles:
    - gather_instances

# Steg 4: Provisionera instanser
- name: Provision instances
  hosts: devops
  connection: local  # Håller ansible från att öppna SSH-anslutningar
  gather_facts: false
  collections:
    - azure.azcollection
  roles:
    - provision_instances
