---

    - name: Install apt-transport-https
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
          - virtualenv
        state: latest
        update_cache: yes

    - name: Add signing key
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: yes
    - name: Install Docker
      apt:
        name:
          - docker.io
          - containerd
        state: latest
        update_cache: yes

    - name: Install Docker Module for Python
      pip:
        name: docker