name: Deploy Microblog

on:
  push:
    tags:
      - 'v*'  # Trigga deployment vid versionstaggar som v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Deploy using Ansible
      run: |
        ansible-playbook -i ansible/hosts ansible/cd-microblog.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
