name: Deploy Microblog

on:
  workflow_dispatch:   # For test running the workflow
  release:
    types: [published]
jobs:
  call_tests:
    name: Call docker image publish
    uses: ./.github/workflows/docker-publish.yml
  deploy:
    runs-on: ubuntu-latest
    needs: call_tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Include Docker Publish Workflow
      uses: ./.github/workflows/docker-publish.yml
      

    
    - name: Setup SSH 
      shell: bash
      run: |
        mkdir -p /home/runner/.ssh/
        touch /home/runner/.ssh/id_rsa
        echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
        chmod 700 /home/runner/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add /home/runner/.ssh/id_rsa

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Deploy using Ansible
      run: |
        ansible-playbook -i ansible/hosts ansible/cd-microblog.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
