name: Security Checks

# Trigger manually using workflow_dispatch
on:
  workflow_dispatch:   # Allows manual triggering of the workflow

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for Docker builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install Bandit, Trivy, Docker, and handle containerd conflict
      - name: Remove conflicting containerd and install dependencies
        run: |
          # Remove any existing containerd package to avoid conflicts
          sudo apt-get remove -y containerd
          sudo apt-get autoremove -y

          # Update apt package list
          sudo apt-get update -qq

          # Install necessary dependencies
          sudo apt-get install -y docker.io wget curl

          # Install Bandit (Python security checks)
          pip install bandit

          # Install Trivy (Docker image security scanner)
          curl -s https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo bash

          # Install Docker (in case it's not already installed)
          curl -fsSL https://get.docker.com | sudo sh

      # Run Bandit for Python security checks
      - name: Run Bandit Security Scan
        run: |
          bandit -r app/ -f html -o bandit-report.html || true

      # Run Trivy for Docker image security scan
      - name: Run Trivy Image Scan
        run: |
          docker build -t microblog . -f docker/Dockerfile_prod
          trivy image --skip-update --no-progress microblog

      # Run Dockle for Docker image security checks
      - name: Run Dockle Security Scan
        run: |
          docker build -t microblog . -f docker/Dockerfile_prod
          docker run --rm -i hadolint/hadolint < docker/Dockerfile_prod
          dockle --exit-code 1 microblog 2>&1 | grep -E 'FATAL|INFO' | sort

      # Optional: Print Bandit Report
      - name: Print Bandit Report
        run: |
          if [ -f bandit-report.html ]; then cat bandit-report.html; fi
