name: Security Checks

# Trigger manually using workflow_dispatch
on:
  workflow_dispatch:   # Allows manual triggering of the workflow

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for Docker builds (if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Remove Docker, containerd, and related packages
      - name: Remove Docker, containerd, and related packages
        run: |
          # Remove Docker and containerd packages completely
          sudo apt-get remove -y docker docker-engine docker.io containerd runc
          sudo apt-get purge -y docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-compose

          # Remove any leftover configuration files and binaries
          sudo rm -rf /etc/bash_completion.d/docker /usr/local/bin/docker-compose /etc/bash_completion.d/docker-compose

          # Clean up any remaining packages
          sudo apt-get autoremove -y
          sudo apt-get clean

          # Update the apt package list
          sudo apt-get update -qq

      # Reinstall Docker and dependencies
      - name: Reinstall Docker, containerd, and docker-compose
        run: |
          # Install containerd, docker, and docker-compose
          sudo apt install -y containerd docker.io docker-compose

          # Install Bandit (Python security checks)
          pip install bandit

          # Install Trivy (Docker image security scanner)
          curl -s https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo bash

          # Install Dockle (Dockerfile security checker)
          curl -s https://github.com/goodwithtech/dockle/releases/download/v0.4.0/dockle-linux-amd64.tar.gz | tar xz && sudo mv dockle /usr/local/bin

      # Run the Bandit security scan using makefile target
      - name: Run Bandit Security Scan
        run: make bandit  # This assumes you have a 'bandit' target in your Makefile

      # Run the Trivy image scan using makefile target
      - name: Run Trivy Image Scan
        run: make image-scan  # This assumes you have an 'image-scan' target in your Makefile

      # Run Dockle security scan using makefile target
      - name: Run Dockle Security Scan
        run: make dockle  # This assumes you have a 'dockle' target in your Makefile

      # Optional: Print Bandit Report if needed
      - name: Print Bandit Report
        run: |
          if [ -f bandit-report.html ]; then cat bandit-report.html; fi
